# Stage 1: Build
FROM golang:nanoserver AS build

# Set the working directory
WORKDIR /app

# Copy Go modules manifest and cache dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# Build the Go executable
RUN go build  -o netpol.exe  ./cmd

# Stage 2: Runtime
FROM mcr.microsoft.com/windows/nanoserver:ltsc2022

WORKDIR /app

COPY --from=build /app/netpol.exe .

CMD ["netpol.exe"]